language: java

before_install:
- chmod +x .buildscript/deploy_snapshot.sh

after_success:
- ".buildscript/deploy_snapshot.sh"

notifications:
  email: false

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  global:
  - MAVEN_OPTS="-Xmx256M"
  - secure: "NTGS2uo7PMlMDx5oATsOQnVfC0H1Q+OY0hZQoxYNk4DcJtIelR7xT4ggHc2zG9Mc5rHkhc25wELKyoLIblqwi6NWUYlLOnU07zCSpy8Wd0Uq5degvlDJXtEX5y4kCDJ+6PZM5z9C8TuvunpmiipFiKH2Yz88sIy8sbZe7iLq6WI="
  - secure: "IlXTC7/I+t11yxXYjgq5cFgOnhKLVBrARl6376bUoSNLRkhAehT7650rFgnnWllrLZyd7Pvcqz/QjDpO8oMXSFR/RNYcElBiPpgVfNoFdnusy8Cq7Ho8ui4MR82IHeR+8wKrbx0mcJCkphkhrBz7CUN9kNN5RAYMO+O2ZhQXYNM="

sudo: false

cache:
  directories:
  - "$HOME/.m2/io"
  - "$HOME/.m2/org"

script: mvn clean install -DperformRelease=false -Dmaven.javadoc.skip=true -B -V -q
  -T 2
