language: java

notifications:
  email: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - MAVEN_OPTS="-Xmx256M"

sudo: false

cache:
  directories:
    - $HOME/.m2/io
    - $HOME/.m2/org

script: mvn clean install -DperformRelease=false -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q -T 2


