language: java

before_install:
- chmod +x .buildscript/deploy_snapshot.sh

after_success:
- ".buildscript/deploy_snapshot.sh"

notifications:
  email: false

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  global:
  - MAVEN_OPTS="-Xmx256M"
  - secure: lD7UFbJD/LS8aNLKrOGxIVRZMUJvxlZ1cW+wJ2qrzMoCzF9zIxFU2R4kuIO0rIcm+9JUXJmCfO/qGieqB46AlpJHKTZc7cDaSgekmE6ZoqepjfgZZ+pukEiBv6WcQ4qSnqcHrNxZQhQlx5VtI8hQDfuSI3tI79XTsxr7VcK9mfU=
  - secure: WCr442njUFi4o9k0DXV88OWPYzW9aYVZdczGmd9z9+kmUk3ySGUDlLOIaE91HrPlnI0RhnXj503YQSaUAIKE62vEXARlZhhzDbRo4p4FK278P6zh0EZ2UlEmaVtAOJHAx3ToCH0I0R1TP/pXgDHsDzl9x8M/WP3SD7z0z/OoLE4=

sudo: false

cache:
  directories:
  - "$HOME/.m2/io"
  - "$HOME/.m2/org"

script: mvn clean install -DperformRelease=false -Dmaven.javadoc.skip=true -B -V -q
  -T 2
