language: java

before_install:
- chmod +x .buildscript/deploy_snapshot.sh

after_success:
- ".buildscript/deploy_snapshot.sh"

notifications:
  email: false

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  global:
  - MAVEN_OPTS="-Xmx256M"
  - secure: "Kz0ki/rdRWAfhCv+33WXoD421OFsmJ8yf/CWo9niB/3tYramqv6OAKvinHSrp2It2RLcStfldC2SKmKa3KUaRmfawImsITzXkXqR6M4VC/p6x4J41euN//EoY0vOgvSB+Q8vLgK8PBReKMtIxU0CWrv39wzJpG4fJSDHtToO4ZQ="
  - secure: "EO4lL2SwL4adcF8F5K+XiU1TeDjFmdUDJQN/HoPxh3TBNrmqV8t40vc1TRQovh0ab+SNP3+TzZuPdWV0H1fDWKtdlROF5rlLKpgZotL2nTX820AbAnIPaTDmVfISanjJ8y7JIBWy2y64t7UH6CxnKWYWhnBas3I/tFxDWN4Ar0A="

sudo: false

cache:
  directories:
  - "$HOME/.m2/io"
  - "$HOME/.m2/org"

script: mvn clean install -DperformRelease=false -Dmaven.javadoc.skip=true -B -V -q
  -T 2
