language: android
android:
  components:
  - build-tools-20.0.0
  - android-19
  licenses:
  - android-sdk-license-5be876d5
branches:
  except:
  - gh-pages
  - travis
notifications:
  email: false
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: ZLQy5m3kuPqAHxdmn4xGP4CsELLCQ0EF+Q+6wNnhvrkRrk8LLffsOAdqamA9GzOjq297f3MyhWaN+8yPutZBRM9+hetJuNLA8naMCrRDJew+xoMuVC8+srnLuG9Bo6fZAu++B/vXMJqLVAec17Yd/mxCIvZwZAO5TChAi8681Rg=
  - secure: PKj+dErhZA9U9uby3Z1yqL6ThP5toKKqiTFlZXVI5QJb2RvVWJ9w6YlessZCAw68bAsAd/QHCk199slgL0iCB6AmeouR9cergj2F93lV+LNaPyfP32UcuTsPew9TZPUpGhRvcIYmlyQNdum4USL8/swkAYOV8f4p9R1GOimoahs=
